all: programa
programa: main TAD-disperseMatrix
	g++ -o Ejecutable main.o TAD-disperseMatrix.o
main: main.cpp
	g++ -c main.cpp
TAD-disperseMatrix: TAD-disperseMatrix.cpp
	g++ -c TAD-disperseMatrix.cpp